// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoPractica.Models;

public partial class Componente
{
    public int Codigo { get; set; }

    public string Nombre { get; set; }

    public DateOnly? FechaBaja { get; set; }

    public string MotivoBaja { get; set; }
}