// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ProyectoPractica.Models;

public partial class DbProduccionContext : DbContext
{
    public DbProduccionContext(DbContextOptions<DbProduccionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Componente> Componentes { get; set; }

    public virtual DbSet<DetallesOrden> DetallesOrdens { get; set; }

    public virtual DbSet<OrdenesProduccion> OrdenesProduccions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Componente>(entity =>
        {
            entity.HasKey(e => e.Codigo).HasName("PK_Table_1");

            entity.Property(e => e.Codigo).HasColumnName("codigo");
            entity.Property(e => e.FechaBaja).HasColumnName("fecha_baja");
            entity.Property(e => e.MotivoBaja)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("motivo_baja");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<DetallesOrden>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.NroOrden });

            entity.ToTable("Detalles_orden");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.NroOrden).HasColumnName("nro_orden");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.Componente).HasColumnName("componente");
        });

        modelBuilder.Entity<OrdenesProduccion>(entity =>
        {
            entity.HasKey(e => e.NroOrden);

            entity.ToTable("Ordenes_produccion");

            entity.Property(e => e.NroOrden).HasColumnName("nro_orden");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("estado");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.Modelo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("modelo");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}