// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoPractica.Models;

public partial class DetallesOrden
{
    public int Id { get; set; }

    public int NroOrden { get; set; }

    public int Componente { get; set; }

    public int Cantidad { get; set; }
}