// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoPractica.Models;

public partial class OrdenesProduccion
{
    public int NroOrden { get; set; }

    public DateOnly Fecha { get; set; }

    public string Modelo { get; set; }

    public string Estado { get; set; }

    public int Cantidad { get; set; }

    public ICollection<DetallesOrden> Detalles { get; set; } = new List<DetallesOrden>();
}